### PR TITLE
Added check whether ancestor method is a Proc

### PR DESCRIPTION
**Pull request by madmike**
I've got a strange error when updated to rails 4.2.6:
TypeError (wrong argument type Fixnum (expected Proc)) in compile_stack method
When i looked deeper i found out that this method test all the ancestors of the OmniAuth::Strategies::XXX (currently using one, e.g. Facebook). Among them there is sure an Object class which had an ancestor of its own a Process class in production environment. So the Process has a uid method which returns the Fixnum class and caused this error.

### CODE REVIEW

**Comment by adin-ttc** [comment]
I have this issue. I'm sure it has something to do with the way our Environment auto loads but I haven't had time to investigate.. This does solve the problem.

**Comment by tmilewski** [comment]
Is this still an issue? If so, would you mind rebasing on Master?

**Comment by adin-ttc** [comment]
@tmilewski this is indeed still an issue.. I will try a rebase

**Comment by BobbyMcWho** [comment]
If this is still an issue, can you make a clean PR? There's a lot of conflicts presently.

**Pull request closed without merging**
