### PR TITLE
Use `session` method instead of `@env['rack.session']`

### PR DESCRIPTION
**Pull request by yui-knk**

### CODE REVIEW

**Comment by nicoolas25** [comment]
It will be very nice for me to configure Omniauth un a way that allows me to use another session key, for instance `rack.production.session` instead of `rack.session`

**Comment by yui-knk** [comment]
If you want to use `rack.production.session` as session key, you can override `#session` method.
And this PR make it easy to override session key :)

**Comment by nicoolas25** [comment]
I just added #819 about this. It includes your patch.

**Comment by nicoolas25** [comment]
Can you make the `rack.session` string a frozen constant?

**Pull request merged**
