### PR TITLE
Release 1.9.1

### PR DESCRIPTION
**Pull request by BobbyMcWho**
Have to do this via PR, since the branch is protected.

### CODE REVIEW

**Comment by supernova32** [comment]
Do you know why Travis is failing? It seems odd, though. Is it passing locally?

**Comment by BobbyMcWho** [comment]
It's not passing locally, rack 2.1.0 and 2.2.0 included some changes that broke a few tests.
[It seems they may not really be an issue](https://github.com/rack/rack/issues/1612#issuecomment-591819697) so I just need to update those specs

**Comment by supernova32** [comment]
I think a better option would be to lock down the rack version used for the tests. It doesn't make sense that a simple change like this breaks the build, just because there is a newer version of rack that is not compatible with our code.

Can you lock it down to the version that works? That way master will be green without having to change the tests.

**Comment by BobbyMcWho** [comment]
Becuase rack is a co-dependency of this package and a ton of others, I don't want to artificially limit the version of rack if possible. We should only pin it of it rack actually merges changes that will fundamentally affect the way this package's code functions

**Comment by supernova32** [comment]
Makes sense. But I also don't want to merge this PR when it will lead to a "broken" master. Could you open a new PR with the test fixes, so we merge that one first?

**Comment by BobbyMcWho** [comment]
Yup, I'm at Lonestar Elixir conf currently, so it'll be a few days most likely til I can look at it

**Comment by supernova32** [comment]
Nice! Have fun!

**Comment by BobbyMcWho** [comment]
@supernova32 can you approve this? I think the coverage check is based on master branch, and so I can't get passed it even though I haven't changed anything that should be tested.

**Review by techdoutdigi21 — CHANGES_REQUESTED** [review]
Check check

**Review by techdoutdigi21 — CHANGES_REQUESTED** [review]
.

**Pull request merged**
