### PR TITLE
Create CHANGELOG

### LINKED ISSUE #756: Why no CHANGELOG?
It's surprising this project doesn't have any CHANGELOG listing important changes across versions. Is there any reason there isn't one? Would you be interested if I started one in a pull request?

PS: I explain [here](http://keepachangelog.com/) why I think this is important.

### PR DESCRIPTION
**Pull request by olivierlacan**
I'm not going to fill out those releases with change log items but at least dates and diff links will be useful to some including me.

My hopes are pointed toward the Unreleased section at the top. :pray: 

Fixes #756

### CODE REVIEW

**Comment by olivierlacan** [comment]
@sferik Any objections on this one?

**Comment by sferik** [comment]
Is this really valuable? It seems like a copy of https://rubygems.org/gems/omniauth/versions that needs to be manually updated and may contain inaccurate information.

**Comment by semaperepelitsa** [comment]
@sferik What about the change log? I don’t know what to look out for when upgrading omniauth.

**Comment by tmilewski** [comment]
Please see my comment here: https://github.com/omniauth/omniauth/issues/756#issuecomment-277494251

**Pull request closed without merging**
