### PR TITLE
Add Truffleruby head to CI

### PR DESCRIPTION
**Pull request by gogainda**

### CODE REVIEW

**Comment by gogainda** [comment]
Tests are passing, but coverage check fails due to https://github.com/oracle/truffleruby/issues/2078

**Comment by gogainda** [comment]
@BobbyMcWho pls review/merge

**Review by BobbyMcWho — CHANGES_REQUESTED** [review]
Can you please add truffleruby-head to the list of allowed failures?

**Comment by gogainda** [comment]
@BobbyMcWho  done

**Review by BobbyMcWho — APPROVED** [review]

**Pull request merged**
