### PR TITLE
Update Gemfile

### PR DESCRIPTION
**Pull request by stnert**

### CODE REVIEW

**Comment by BobbyMcWho** [comment]
Is there a reason you're looking to add a rails specific dependency to this gem?

**Comment by stnert** [comment]
> Is there a reason you're looking to add a rails specific dependency to this gem?

Yes, I have detected a vulnerability present in the code.

**Comment by BobbyMcWho** [comment]
Well the gem you are looking to add is a rails specific gem that configures secure CSRF token callbacks in omniauth for Rails framework apps. It does not resolve any CVE currently present in the latest release of OmniAuth.

**Comment by stnert** [comment]
Alright, I ended up updating just in case, I decided to rely on the Dependbot I added to my Github for the forks I do, get it?

**Comment by stnert** [comment]
> Well the gem you are looking to add is a rails specific gem that configures secure CSRF token callbacks in omniauth for Rails framework apps. It does not resolve any CVE currently present in the latest release of OmniAuth.

**Pull request closed without merging**
