### PR TITLE
Set params when mocking a failure

### LINKED ISSUE #811: omniauth.params is not being set when mocking failure
Similar to the issue fixed by 32eed3b617f304472303382a7dfb511ba6483892, we expect `omniauth.params` to be set on failure.

Pull request coming shortly.

### PR DESCRIPTION
**Pull request by afn**
Fixes #811

### CODE REVIEW

**Comment by afn** [comment]
Can this be merged?

**Comment by booleanbetrayal** [comment]
Please merge! Having to monkeypatch omniauth in an authentication library just to have appropriate test coverage!

**Comment by barillax** [comment]
:+1: on merging from my perspective!

**Comment by afn** [comment]
Can this be merged, or are there any outstanding issues with the PR?

Thanks!
Tony

**Comment by booleanbetrayal** [comment]
anything holding this PR up?

**Comment by afn** [comment]
Please let me know if you need me to make any changes before this can be merged.

Thanks!

**Pull request merged**
